import { Inter } from "next/font/google";
import "../../../src/app/globals.css";
import SideBar from "@/components/Sidebar";
import StoreProvider from "../StoreProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News Scrapper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar />
          <div className="lg:flex  ">
            <div className="lg:mt-14">
              <SideBar />
            </div>
            <div className=" lg:ml-56 ">{children}</div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
