import { Inter } from "next/font/google";
import "../../../src/app/globals.css";
import SideBar from "@/components/Sidebar";
import StoreProvider from "../StoreProvider";
import Navbar from "@/components/Navbar_2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar/>
          <div className="   ">{children}</div>
        </StoreProvider>
      </body>
    </html>
  );
}
